name: Tests
on: push
jobs:
  jest:
    name: Jest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Dependencies
      run: npm ci
    - name: Jest
      run: npm run test